# site
headerLogoUrl: /images/logo.png
footerLogoUrl: /images/logo-hsuping.png
favicon: /images/favicon.png
iosicon: /images/apple-touch-icon.png
since: 2018

# menu
menu:
  categories: /categories
  tags: /tags
  archives: /archives
  links: /links
  about: /about

# archive
archive: month

# social
social:
  weibo: /
  zhihu: https://www.zhihu.com/people/52c7f85cb2abafde0b78124e21a68002
  rss: /atom.xml
  github: https://github.com/cccyb
  twitter: /

enablePjax: true
dnsPrefetch: true
enableFastClick: true
postListSwitch: one
colorBgPosts: true
showPostThumb: true
relatedPosts: 
  enable: true
  limit: 6
enableDirectory: true
highlight:
  enable: true
  theme: atom-one-dark
enableMathjax: true
googleAnalytics:
cdnAdd:
defaultThumb: 
randomThumb: 18 # 0 to disable
animateWords:
  - Front-End
  - JavaScript
  - HTML & CSS
  - Node.js
  - React
  - passion & love
recentlyPosts:
  enable: true
  limit: 8
